# overwrite default prefix key
set -g prefix C-t

##### tmux theme
set -g status on
set -g status-interval 1
set -g status-fg default
set -g status-bg default
set -g status-justify "left"
set -g status-position top
set -g status-left-length 160
set -g status-right-length 300

# ----- Messages -----
set-option -g mode-style 'bg=blue, fg=black'
set-option -g message-style 'bg=blue, fg=black'

# ----- Center -----
set-option -g status-style "bg=default"
set-window-option -g window-status-separator ''

set-window-option -g window-status-current-format "#[fg=blue,bg=default]\
#{?window_flags,#{window_flags},} 󰓩 #I:\
#[fg=black,bg=blue]  #W  #[fg=blue,bg=default]"

set-window-option -g window-status-format "#[fg=colour242,bg=default]\
#{?window_flags,#{window_flags},} 󰓪 #I:\
#[fg=black,bg=colour242]  #W  #[fg=colour242,bg=default]"

# ----- Left ----
set-option -g status-left-style "bg=default,fg=default"
set-option -g status-left "#[fg=black,bg=blue]  tmux Session: #S #[fg=blue,bg=default]#[fg=default,bg=default]  "
# ----- Right ----
set-option -g status-right "#[fg=colour242,bg=default]#[fg=black,bg=colour242] 󰛳 #H \
#[bg=blue] #(date)\
#{?pane_in_mode,#[bg=yellow] #{pane_mode},#[bg=blue] default} "

set-option -g focus-events on


##### plugin manager
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reload Config!!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @plugin 'dominikduda/tmux_mode_indicator'
set -g @mode_indicator_prefix '⚡ '

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm

##### something

# reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf reloaded"


# POPUP WINDOWS
# These two shortcuts provide popup windows in tmux. The lowercase version
# makes a popup that named uniquely to the working directory. This is great
# for making a popup window in a coding project.
#
# The uppercase version makes a "global" popup window. Great for persisting
# things globally for a long period of time.
# 
# refs: https://github.com/ianchesal/dotfiles/blob/e2b7f01fcf74dafc683274522c35c5ef5e8e801b/tmux/tmux.conf#L131
bind g run-shell '\
    POPUP_NAME="popup-$(basename "#{pane_current_path}" | tr -cd "a-zA-Z0-9-")"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'

bind G run-shell '\
    POPUP_NAME="popup-global"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'
