
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

# filetypes

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # toml syntax
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_i = 1
hook_add = '''
	" Insertモード時のみ判定
	let g:precious_enable_switch_CursorMoved = { '*': 0, 'help': 1 }
	" INSERTモードのON／OFFに合わせてトグル
	au LocalAutoCmd InsertEnter * :PreciousSwitch
	au LocalAutoCmd InsertLeave * :PreciousReset
'''

